source 'https://github.com/CocoaPods/Specs.git'



platform :ios, '9.0'



use_frameworks!

target 'JJCodeTestLib_Example' do
  pod 'JJCodeTestLib', :path => '../'

  target 'JJCodeTestLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'MBProgressHUD'
  end
end
